name: Node.js CI

on:
  push:
    branches:
      - main  # Verander dit naar de naam van je default branch als dit niet 'main' is
  pull_request:
    branches:
      - main  # Verander dit naar de naam van je default branch als dit niet 'main' is

jobs:
  build:

    runs-on: ${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]  # Pas dit aan naar welke Node.js versies je wilt testen
        os: [macos-latest, windows-latest, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test:coverage  # Dit is het commando om de test coverage te starten, aanpassen indien nodig
